# DevSwap.live Full-Stack Docker Compose
version: "3.8"

services:
  backend:
    build:
      context: ./server
    container_name: devswap-backend
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/devswap
      - REDIS_URL=redis://:$(REDIS_PASSWORD)@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - devswap
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./Frontend
    container_name: devswap-frontend
    environment:
      # If your Vite app needs API URL at build time, export it like below
      # VITE_API_BASE_URL: http://localhost:5000
      - NODE_ENV=production
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - devswap
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: devswap-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=devswap
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - devswap
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: devswap-redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:-}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - devswap
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:

networks:
  devswap:
    driver: bridge
