version: '3.8'

services:
  # Main application
  devswap-backend:
    build: .
    container_name: devswap-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - devswap-network
    # Resource limits for EC2 free tier (1GB RAM)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # MongoDB service
  mongodb:
    image: mongo:7
    container_name: devswap-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=devswap123
      - MONGO_INITDB_DATABASE=devswap
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - devswap-network
    # Resource limits for EC2 free tier
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Redis service
  redis:
    image: redis:7-alpine
    container_name: devswap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - devswap-network
    # Resource limits for EC2 free tier
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    command: redis-server --appendonly yes --maxmemory 100mb --maxmemory-policy allkeys-lru

  # Nginx reverse proxy (optional but recommended)
  nginx:
    image: nginx:alpine
    container_name: devswap-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - devswap-backend
    restart: unless-stopped
    networks:
      - devswap-network
    # Minimal resources for nginx
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  devswap-network:
    driver: bridge
